on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install
      - run: ./node_modules/.bin/eslint ./src/ --ext .js,.jsx,.ts,.tsx